/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutItemsRouteImport } from './routes/app/_layout/items'
import { Route as AppLayoutCalendarRouteImport } from './routes/app/_layout/calendar'
import { Route as AppLayoutActionsRouteImport } from './routes/app/_layout/actions'
import { Route as AppLayoutHistoryDateRouteImport } from './routes/app/_layout/history/$date'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutItemsRoute = AppLayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCalendarRoute = AppLayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutActionsRoute = AppLayoutActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutHistoryDateRoute = AppLayoutHistoryDateRouteImport.update({
  id: '/history/$date',
  path: '/history/$date',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/actions': typeof AppLayoutActionsRoute
  '/app/calendar': typeof AppLayoutCalendarRoute
  '/app/items': typeof AppLayoutItemsRoute
  '/app/history/$date': typeof AppLayoutHistoryDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/actions': typeof AppLayoutActionsRoute
  '/app/calendar': typeof AppLayoutCalendarRoute
  '/app/items': typeof AppLayoutItemsRoute
  '/app/history/$date': typeof AppLayoutHistoryDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/actions': typeof AppLayoutActionsRoute
  '/app/_layout/calendar': typeof AppLayoutCalendarRoute
  '/app/_layout/items': typeof AppLayoutItemsRoute
  '/app/_layout/history/$date': typeof AppLayoutHistoryDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/actions'
    | '/app/calendar'
    | '/app/items'
    | '/app/history/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/actions'
    | '/app/calendar'
    | '/app/items'
    | '/app/history/$date'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/app/_layout'
    | '/app/_layout/actions'
    | '/app/_layout/calendar'
    | '/app/_layout/items'
    | '/app/_layout/history/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/items': {
      id: '/app/_layout/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppLayoutItemsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/calendar': {
      id: '/app/_layout/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppLayoutCalendarRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/actions': {
      id: '/app/_layout/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppLayoutActionsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/history/$date': {
      id: '/app/_layout/history/$date'
      path: '/history/$date'
      fullPath: '/app/history/$date'
      preLoaderRoute: typeof AppLayoutHistoryDateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutActionsRoute: typeof AppLayoutActionsRoute
  AppLayoutCalendarRoute: typeof AppLayoutCalendarRoute
  AppLayoutItemsRoute: typeof AppLayoutItemsRoute
  AppLayoutHistoryDateRoute: typeof AppLayoutHistoryDateRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutActionsRoute: AppLayoutActionsRoute,
  AppLayoutCalendarRoute: AppLayoutCalendarRoute,
  AppLayoutItemsRoute: AppLayoutItemsRoute,
  AppLayoutHistoryDateRoute: AppLayoutHistoryDateRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
